class SignUpLocators:
    """ Locators for sign up page """
    first_nameField = "firstname"
    last_nameField = "lastname"
    phoneOrEmailField = "reg_email__"
    email_confirmation = 'reg_email_confirmation__'
    passwordNewField = "reg_passwd__"
    birthdayField_day = "day"
    birthdayField_month = "month"
    birthdayField_year = "year"
    genderField_female = "_8esa"
    genderField_male = "input[value='2']"
    genderField_custom = "input[value='-1']"
    signUpButton = "websubmit"
    resultMessage = ".uiHeaderTitle"
    BodyPronounField = "//body[1]/div[3]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[1]/div[8]/div[1]/select[1]"